spring:
  application:
    name: pizza-details
  data:
    mongodb:
      uri: mongodb://mongodbservice:27017/pizza_db
server:
  port: 8084
eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka
        fetchRegistry: true
        registerWithEureka: true
#    instance:
#      hostname: localhost