server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://mysqlservice:3306/registered_users?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect

  application:
    name: user-register-detail
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
#  instance:
#    hostname: localhost
#instance not needed for docker